### ISSUE TITLE
Typescript throws errors

### ISSUE THREAD

**Issue by jameskentTX** [sindresorhus/read-chunk#14]
Typescript (Version 3.3.3333, node v10.15.3) can't compile read-chunk folder in node-modules:

cd node_modules/read-chunk
tsc

Output:

../../e2e/app.e2e-spec.ts:12:45 - error TS2345: Argument of type '"Weather module"' is not assignable to parameter of type 'Expected<Promise<string>>'.
12     expect(page.getParagraphText()).toEqual('Weather module');
                                               ~~~~~~~~~~~~~~~~
../../server/controllers/profile.ts:301:38 - error TS2339: Property 'sync' does not exist on type 'typeof import("/home/leszek/smartDating/node_modules/read-chunk/index")'.
301             const buffer = readChunk.sync(req.file.path, 0, 262);
                                         ~~~~
../../server/controllers/profile.ts:302:26 - error TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'typeof import("/home/leszek/smartDating/node_modules/file-type/index")' has no compatible call signatures.
302             myFileType = fileType(buffer);
                             ~~~~~~~~~~~~~~~~
Found 3 errors.

**Comment by sindresorhus** [comment]
The types are tested to work. So you're doing something wrong. There are better channels than an issue for TS support.

https://github.com/sindresorhus/read-chunk/blob/master/index.test-d.ts

Make sure you import it as `import readChunk from 'read-chunk';`.

**Comment by jameskentTX** [comment]
Thanks sindresorhus, your response helped.
I changed "import * as readChunk from 'read-chunk';" to "import readChunk from 'read-chunk';" and errors disappeared.
