### ISSUE TITLE
Why New Versions of Library only Exported as ESM Module and not Common JS Module

### ISSUE THREAD

**Issue by jugnu-appveen** [sindresorhus/read-chunk#20]
I have a code base of node 14. I want to only upgrade the library to fix the vulnerabilities. My code base is based on CommonJS imports. Now installing the new version will break everything.

Could you please help, on how can I fix the vulnerabilities by not upgrading to the latest?

Thanks,
Jugnu

**Comment by sindresorhus** [comment]
Look at `2`: https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
